services:
  db:
    container_name: db
    image: postgres
    restart: always

    volumes:
      - pgdata:/var/lib/postgresql/data 
    ports:
      - '0.0.0.0:5432:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    environment:
      POSTGRES_DB: "db"
      POSTGRES_USER: "user"  
      POSTGRES_PASSWORD: "pass"  

  api:
    container_name: api
    build: api/
    ports:
      - '0.0.0.0:8000:5000'
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: "5432"
      POSTGRES_USER: "user"  
      POSTGRES_PASSWORD: "pass"  
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      ax/
    ports:
      - '3000:3000'

volumes:
  pgdata:
